export enum TreeNodeType {
  CONTAINER = 'CONTAINER',
  CONCEPT_FOLDER= 'CONCEPT_FOLDER',
  CONCEPT = 'CONCEPT',
  MODIFIER = 'MODIFIER',
  MODIFIER_FOLDER = 'MODIFIER_FOLDER',
  MODIFIER_CONTAINER = 'MODIFIER_CONTAINER',
  GENOMIC_ANNOTATION = 'GENOMIC_ANNOTATION',
  UNKNOWN = 'UNKNOWN'
}
